# This is a basic workflow to help you get started with Actions

name: CI/CD STAGING

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [staging]
  pull_request:
    branches: [none]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    name: 'Deploy to STAGING'
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
          cat >>~/.ssh/config <<END
          Host myserver
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/private.key
            StrictHostKeyChecking no
            Port $PORT
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          PORT: ${{ secrets.PORT }}

      - name: Deploying into server
        run: |
          ssh myserver 'cd /home/sairam/imelda_frontend_staging && git reset --hard && git pull origin staging && npm install --force && npm run build && rm -rf /home/sairam/imelda_frontend_staging/output && cp -ar /home/sairam/imelda_frontend_staging/dist /home/sairam/imelda_frontend_staging/output && pm2 restart STAGING'
      - run: echo "🎉 Deployed successfully."
